nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

packageExtensions:
  "@storybook/addon-essentials@*":
    peerDependencies:
      react: "*"
      react-dom: "*"

  "@storybook/addon-controls@*":
    peerDependencies:
      react: "*"
      react-dom: "*"

  "@storybook/manager-api@*":
    peerDependencies:
      react: "*"
      react-dom: "*"

  "@storybook/react-vite@*":
    peerDependencies:
      typescript: "*"

  "@storybook/cli@*":
    peerDependencies:
      react: "*"
      react-dom: "*"

  "@storybook/core-server@*":
    peerDependencies:
      react: "*"
      react-dom: "*"

  "storybook@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
