nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

packageExtensions:
  "@storybook/addon-docs@*":
    peerDependencies:
      "@types/react": "*"
      "@types/react-dom": "*"
  "@storybook/react-vite@*":
    peerDependencies:
      typescript: "*"
  storybook@*:
    peerDependencies:
      "@testing-library/dom": "*"
