nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

packageExtensions:
  "@storybook/addon-docs@*":
    peerDependencies:
      "@types/react": "*"
      "@types/react-dom": "*"

  "@storybook/addon-essentials@*":
    peerDependencies:
      "@types/react": "*"
      "@types/react-dom": "*"

  "@storybook/core@*":
    peerDependencies:
      storybook: "*"

  "@storybook/react-vite@*":
    peerDependencies:
      typescript: "*"
