# SonarQube properties
sonar.projectKey=NHSDigital_nhsuk-react-components
sonar.organization=nhsdigital

# Project language
sonar.language=js

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
