import * as index from '../index';

describe('Index', () => {
  it('contains all expected elements', () => {
    const sortedIndex = Object.keys(index).sort((a, b) => a.localeCompare(b));

    expect(sortedIndex).toEqual([
      'ActionLink',
      'ArrowLeftIcon',
      'ArrowRightCircleIcon',
      'ArrowRightIcon',
      'BackLink',
      'BodyText',
      'Breadcrumb',
      'Button',
      'Card',
      'CharacterCount',
      'CharacterCountType',
      'Checkboxes',
      'Clearfix',
      'Col',
      'Container',
      'ContentsList',
      'CrossIcon',
      'DateInput',
      'Details',
      'DoAndDontList',
      'ErrorMessage',
      'ErrorSummary',
      'Fieldset',
      'Footer',
      'Form',
      'FormGroup',
      'Header',
      'Hero',
      'HintText',
      'Images',
      'InsetText',
      'Label',
      'LedeText',
      'NavAZ',
      'Pagination',
      'Panel',
      'Radios',
      'ReadingWidth',
      'ReviewDate',
      'Row',
      'SearchIcon',
      'Select',
      'SkipLink',
      'SummaryList',
      'Table',
      'Tabs',
      'Tag',
      'Textarea',
      'TextInput',
      'TickIcon',
      'useFormContext',
      'WarningCallout',
    ]);
  });
});
