name: CD Build and Publish to NPM

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Enable corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          cache: yarn
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org/

      - name: Yarn Install
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Jest Tests
        run: yarn test --coverage

      - name: Package build
        run: yarn build
        env:
          NODE_ENV: production

      - name: Publish npm package
        if: ${{ !github.event.release.prerelease }}
        run: npm publish --tag latest

      - name: Publish npm package (pre-release)
        if: ${{ github.event.release.prerelease }}
        run: npm publish --tag beta
